version: '3.4'

services:
  server:
    image: wirvonhier/server:0.1.0
    build: ./server
    networks:
      - server
    logging: # TODO
    environment:
        CLIENT_BASE_URL: https://test.wirvonhier.net
        APP_DOMAIN: wirvonhier.net
        NODE_ENV: production
        MONGO_INITDB_ROOT_USERNAME: admin # SECRET
        MONGO_INITDB_ROOT_PASSWORD: pass # SECRET
        MONGO_INITDB_DATABASE: wirvonhier
        PORT: 3000
        MONGO_USER: wirvonhier # SECRET
        MONGO_PASSWORD: wirvonhierpass # SECRET
        MONGO_PATH: mongo:27017/wirvonhier
        MONGO_AUTH_SOURCE: wirvonhier
        SENDGRID_API_KEY: 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 # SECRET
        CLOUDINARY_CLOUD_NAME: wirvonhier
        CLOUDINARY_API_KEY: 545333192328677 # SECRET
        CLOUDINARY_API_SECRET: 7lDUL7rWerwKu42ahbhvceDYq7E # SECRET
        VIMEO_ACCESS_TOKEN: 18ddc1f86ce274df9854fa1a2897e5cc # SECRET
    deploy:
      endpoint_mode: dnsrr
      mode: "replicated"
      resource:
        limits:
          memory: 4G

  client:
    image: wirvonhier/client:0.1.0
    build: ./client
    networks:
      - client
    logging: # TODO
    ports:
      - 8080:8080
    environment:
      API_URL: https://api.wirvonhier.net
      CLOUDINARY_CLOUD_NAME: wirvonhier
      IMAGE_UPLOAD_URL: https://api.cloudinary.com/v1_1/wirvonhier/image/upload
      CLOUDINARY_IMAGE_PRESET: wirvonhier_image
      GOOGLE_MAPS_API_KEY: AIzaSyAXjnxppLHFrUJ12rsVOdJWihTavWHWyMA # SECRET
    deploy:
      endpoint_mode: dnsrr
      mode: "replicated"
      resource:
        limits:
          memory: 4G

  proxy:
    image: wirvonhier/nginx:1.0.0
    restart: always
    networks:
      - client
      - server
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    logging: # TODO
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    depends_on:
      - server
    deploy:
      endpoint_mode: dnsrr
      mode: "replicated"
      resource:
        limits:
          memory: 4G

  mongo:
    image: wirvonhier/mongo:0.1.0
    networks:
      - server
    logging: # TODO
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin # TODO: move to secret (github secrets?)
      MONGO_INITDB_ROOT_PASSWORD: pass # TODO: move to secret
      MONGO_INITDB_DATABASE: wirvonhier # TODO: move to secret
    volumes:
      - mongodbdata:/data/db
    deploy:
      endpoint_mode: dnsrr
      mode: "replicated"
      resource:
        limits:
          memory: 4G

volumes:
  mongodbdata: # get this off this node? -> if multiple mongo nodes this is required

networks:
  client:
  server:

secrets: # TODO