version: '3.4'

services:
  server:
    image: node:12
    working_dir: /home/node/app
    command: ./node_modules/.bin/nodemon --inspect=0.0.0.0:9229 src/index.ts
    ports:
      - "9229:9229"
    volumes:
      - ./server:/home/node/app:delegated
      - server_nodemodules:/home/node/app/node_modules
    entrypoint: bash /home/node/app/docker-entrypoint.sh
    networks:
      - server
    secrets:
      - mongo_user
      - mongo_password
      - sendgrid_api_key
      - cloudinary_api_key
      - cloudinary_api_secret
      - vimeo_access_token
      - google_maps_api_key
    environment:
      NODE_ENV: development
      CLIENT_BASE_URL: https://localhost
      APP_DOMAIN: localhost
      PORT: 3000
      MONGO_USER_FILE: /run/secrets/mongo_user
      MONGO_PASSWORD_FILE: /run/secrets/mongo_password
      MONGO_PATH: mongo:27017/wirvonhier
      MONGO_AUTH_SOURCE: wirvonhier
      SENDGRID_API_KEY_FILE: /run/secrets/sendgrid_api_key
      CLOUDINARY_CLOUD_NAME: wirvonhier
      CLOUDINARY_API_KEY_FILE: /run/secrets/cloudinary_api_key
      CLOUDINARY_API_SECRET_FILE: /run/secrets/cloudinary_api_secret
      VIMEO_ACCESS_TOKEN_FILE: /run/secrets/vimeo_access_token

  client:
    image: node:12
    working_dir: /home/node/app
    command: npm run dev
    volumes:
      - ./client:/home/node/app:delegated
      - client_nodemodules:/home/node/app/node_modules
    entrypoint: bash /home/node/app/docker-entrypoint.sh
    networks:
      - client
    secrets:
      - google_maps_api_key
    environment:
      API_URL: https://localhost/server
      CLOUDINARY_CLOUD_NAME: wirvonhier
      IMAGE_UPLOAD_URL: https://api.cloudinary.com/v1_1/wirvonhier/image/upload
      CLOUDINARY_IMAGE_PRESET: wirvonhier_dev
      GOOGLE_MAPS_API_KEY_FILE: /run/secrets/google_maps_api_key

  proxy:
    build: proxy
    image: wirvonhier/nginx:1.0.0
    restart: always
    volumes:
      - ./proxy/wirvonhier.dev.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/localcerts/localhost.pem:/etc/nginx/certs/localhost.pem
      - ./proxy/localcerts/localhost-key.pem:/etc/nginx/certs/localhost-key.pem
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    networks:
      - server
      - client
    depends_on:
      - server
      - client

  mongo:
    image: mongo:latest
    command: --quiet
    networks:
      - server
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: wirvonhier
    volumes:
      - mongodbdata:/data/db:cached
      - ./mongo/seedUser.js:/docker-entrypoint-initdb.d/1.js:ro
    logging:
      driver: none

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - server
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
    depends_on:
      - mongo

volumes:
  mongodbdata:
  client_nodemodules:
    external: true
  server_nodemodules:
    external: true

networks:
  client:
  server:

secrets:
  mongo_user:
    file: ./server/secrets/mongo_user
  mongo_password:
    file: ./server/secrets/mongo_password
  sendgrid_api_key:
    file: ./server/secrets/sendgrid_api_key
  cloudinary_api_key:
    file: ./server/secrets/cloudinary_api_key
  cloudinary_api_secret:
    file: ./server/secrets/cloudinary_api_secret
  vimeo_access_token:
    file: ./server/secrets/vimeo_access_token
  google_maps_api_key:
    file: ./client/secrets/google_maps_api_key
  